title: CPRO
url: https://www.cpro.gov.sg
favicon: /images/icon.jpg
colors:
  primary-color: "#26265b"
  secondary-color: "#595959"
  media-colors:
    - title: media-color-one
      color: "#5c6483"
    - title: media-color-two
      color: "#5c6483"
    - title: media-color-three
      color: "#00838f"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
resources_name: media-centre
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
description: ""
staging: https://mccy-cpro-staging.netlify.app
prod: https://mccy-cpro-prod.netlify.app
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
shareicon: /images/isomer-logo.svg
is_government: false
facebook-pixel: ""
google_analytics: ""
google_analytics_ga4: ""
linkedin-insights: ""
